"""add_lens_brand_coating_to_prescriptions

Revision ID: fae1679855f7
Revises: db4aaf8512b0
Create Date: 2026-09-28 23:09:07.813912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae1679855f7'
down_revision: Union[str, Sequence[str], None] = 'db4aaf8512b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('lens_brand', sa.String(), nullable=True))
    op.add_column('prescriptions', sa.Column('lens_coating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'lens_coating')
    op.drop_column('prescriptions', 'lens_brand')
    # ### end Alembic commands ###
